//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vpn_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub request_id: String,
    pub location_code: String,
    pub location_city: String,
    pub location_city_code: String,
    pub location_country: String,
    pub location_country_code: String,
    pub location_state: Option<String>,
    pub location_state_code: Option<String>,
    pub server_status: Option<String>,
    pub session_uuid: Option<String>,
    pub server_ipv4_endpoint: Option<String>,
    pub server_private_ipv4: Option<String>,
    pub server_public_key: Option<String>,
    pub requested_at: String,
    pub mark_for_deletion: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
