// Copyright 2024 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: GPL-3.0-only

#[allow(unused)]
pub mod vars {
    pub const NYXD_WS: &str = "NYXD_WS";
    pub const NYXD: &str = "NYXD";

    pub const NYM_DATA_OBSERVATORY_NO_BANNER_ARG: &str = "NYM_DATA_OBSERVATORY_NO_BANNER";
    pub const NYM_DATA_OBSERVATORY_CONFIG_ENV_FILE_ARG: &str =
        "NYM_DATA_OBSERVATORY_CONFIG_ENV_FILE_ARG";

    pub const NYM_DATA_OBSERVATORY_DB_URL: &str = "NYM_DATA_OBSERVATORY_DB_URL";

    pub const NYXD_SCRAPER_START_HEIGHT: &str = "NYXD_SCRAPER_START_HEIGHT";
    pub const NYXD_SCRAPER_USE_BEST_EFFORT_START_HEIGHT: &str =
        "NYXD_SCRAPER_USE_BEST_EFFORT_START_HEIGHT";

    pub const NYM_DATA_OBSERVATORY_ID_ARG: &str = "NYM_DATA_OBSERVATORY_ID";
    pub const NYM_DATA_OBSERVATORY_OUTPUT_ARG: &str = "NYM_DATA_OBSERVATORY_OUTPUT";

    pub const NYM_DATA_OBSERVATORY_CONFIG_PATH_ARG: &str = "NYM_DATA_OBSERVATORY_CONFIG";

    pub const NYM_DATA_OBSERVATORY_WATCH_CHAIN_MESSAGE_TYPES: &str =
        "NYM_DATA_OBSERVATORY_WATCH_CHAIN_MESSAGE_TYPES";
    pub const NYM_DATA_OBSERVATORY_WEBHOOK_URL: &str = "NYM_DATA_OBSERVATORY_WEBHOOK_URL";
    pub const NYM_DATA_OBSERVATORY_WEBHOOK_AUTH: &str = "NYM_DATA_OBSERVATORY_WEBHOOK_AUTH";
}
