// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainInteractionCapabilities } from "./ChainInteractionCapabilities";

export type ConfigScoreV2 = { 
/**
 * Total score after taking all the criteria into consideration
 */
score: number, versions_behind: number | null, self_described_api_available: boolean, accepted_terms_and_conditions: boolean, runs_nym_node_binary: boolean, 
/**
 * Describes the node is capable of sending chain/contract transactions
 */
chain_interaction_capabilities: ChainInteractionCapabilities, };
