// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplayRole = "entryGateway" | "layer1" | "layer2" | "layer3" | "exitGateway" | "standby";
