// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetailedNodePerformance } from "./DetailedNodePerformance";
import type { DisplayRole } from "./DisplayRole";

export type NodeAnnotation = { last_24h_performance: string, current_role: DisplayRole | null, detailed_performance: DetailedNodePerformance, };
