// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetailedNodePerformanceV1 } from "./DetailedNodePerformanceV1";
import type { DisplayRole } from "./DisplayRole";

export type NodeAnnotationV1 = { last_24h_performance: string, current_role: DisplayRole | null, detailed_performance: DetailedNodePerformanceV1, };
