// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StressTestingScore = { score: number, 
/**
 * Distinguishes a genuine zero score (node was tested and scored 0) from
 * "node was unreachable" (no successful sample was collected). Consumers may use
 * this to decide whether to penalise the node or treat the score as missing.
 */
was_reachable: boolean, };
