#!/bin/sh

default_location="/usr/bin/nym-gateway"
default_user="nym"
default_group="nym"

# We're assuming there's only two binaries on the machine, one is the newly installed app package version, and the second the existing binary, thus the logic below applies
existing_binaries=$(sudo find / \( -path /proc -o -path /sys -o -path /dev -o -path /mnt -o -path /media \) -prune -o -type f -name "nym-gateway" -print 2>/dev/null)
oldest_binary=$(ls -ltr $existing_binaries | head -n 1 | awk '{print $NF}')

if [ -n "$oldest_binary" ] && [ "$oldest_binary" != "$default_location" ]; then
    echo "Existing binary found at $oldest_binary"

    backup_path="${oldest_binary}.backup.$(date +%Y-%m-%dT%H:%M:%S%z)"
    echo "Backing up the original binary to $backup_path"
    sudo cp "$oldest_binary" "$backup_path"

    original_user=$(stat -c "%U" "$oldest_binary")
    original_group=$(stat -c "%G" "$oldest_binary")

    echo "Original group: $original_group"
    echo "Original user: $original_user"

    echo "Moving new binary from $default_location to $oldest_binary"
    mv "$default_location" "$oldest_binary"

    echo "Changing ownership to $original_user:$original_group"
    chown "$original_user:$original_group" "$oldest_binary"

    original_perms=$(stat -c "%a" "$backup_path")
    echo "Setting permissions to $original_perms"
    chmod "$original_perms" "$oldest_binary"

    echo "Please restart the nym-gateway process to apply changes."
    echo "Sometimes the gateways will require a re-init, but comms during releases should highlight this."
    echo "Usually: systemctl restart nym-gateway.service"

elif [ ! -f "$default_location" ]; then
    echo "No existing binary found, performing first-time installation."

    if [ -f "/usr/bin/nym-gateway" ]; then
        echo "Moving new binary to $default_location"
        mv "/usr/bin/nym-gateway" "$default_location"

        echo "Setting default ownership to $default_user:$default_group"
        chown "$default_user:$default_group" "$default_location"

        echo "Setting default permissions"
        chmod 755 "$default_location"

        echo "Installation complete. Please configure and start the nym-gateway process manually."
        echo "Please refer to https://nymtech.net/operators/nodes/gateway-setup.html"
    else
        echo "Error: the new binary /usr/bin/nym-gateway does not exist."
    fi
else
    echo "The binary is already in the expected location ($default_location). No action taken."
fi

#DEBHELPER#