// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidatorUrl } from './ValidatorUrl';

export interface ValidatorUrls {
  urls: Array<ValidatorUrl>;
}
