/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_SOCKS5_C__
#define __RUST_SOCKS5_C__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
typedef enum ClientState {
    /** <No documentation available> */
    CLIENT_STATE_UNKNOWN,
    /** <No documentation available> */
    CLIENT_STATE_CONNECTED,
    /** <No documentation available> */
    CLIENT_STATE_DISCONNECTED,
} ClientState_t;

/** <No documentation available> */
void
blocking_run_client (
    char const * storage_directory,
    char const * service_provider,
    void (*on_start_callback)(char *),
    void (*on_shutdown_callback)(void));

/** <No documentation available> */
void
reset_client_data (
    char const * root_directory);

/** <No documentation available> */
void
rust_free_string (
    char * string);

/** <No documentation available> */
void
start_client (
    char const * storage_directory,
    char const * service_provider,
    void (*on_start_callback)(char *),
    void (*on_shutdown_callback)(void));

/** <No documentation available> */
void
stop_client (void);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_SOCKS5_C__ */
