// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coin } from './Coin';

export type CosmosFee = { amount: Array<Coin>; gas_limit: bigint; payer: string | null; granter: string | null };
