// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeclaredRolesV1 = { mixnode: boolean, entry: boolean, exit_nr: boolean, exit_ipr: boolean, };
