// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecCoin } from './DecCoin';

export interface Delegation {
  owner: string;
  node_identity: string;
  amount: DecCoin;
  block_height: bigint;
  proxy: string | null;
}
