// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigScore } from "./ConfigScore";
import type { RoutingScore } from "./RoutingScore";
import type { StressTestingScore } from "./StressTestingScore";

export type DetailedNodePerformanceV2 = { 
/**
 * routing_score * config_score
 * or
 * routing_score * config_score * stress_testing_score, if enabled
 */
performance_score: number, routing_score: RoutingScore, config_score: ConfigScore, stress_testing_score: StressTestingScore, };
