// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal status for an invitation that has been moved out of the pending set.
 *
 * Note: an invitation that merely times out is **not** archived here on its own —
 * it is left inert in the pending set (see `FamilyInvitation::expires_at`). It only
 * reaches `Expired` if the family issues a fresh invitation for the same node, which
 * supersedes and archives the stale one.
 */
export type FamilyInvitationStatus = { "pending": { at: number, } } | { "accepted": { at: number, } } | { "rejected": { at: number, } } | { "revoked": { at: number, } };
