// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CosmosFee } from "./CosmosFee";

export type Fee = { "Manual": CosmosFee } | { "Auto": number | null };
