// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gas } from './Gas';

export interface GasInfo {
  gas_wanted: Gas;
  gas_used: Gas;
}
