// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GatewayConfigUpdate = {
  host: string;
  mix_port: number;
  clients_port: number;
  location: string;
  version: string;
};
