// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MixNodeConfigUpdate = {
  host: string;
  mix_port: number;
  verloc_port: number;
  http_api_port: number;
  version: string;
};
