// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecCoin } from './DecCoin';

export type NodeCostParams = { profit_margin_percent: string; interval_operating_cost: DecCoin };
