// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information provided by the node operator during bonding that are used to allow other entities to use the services of this node.
 */
export type MixNode = {
  /**
   * Network address of this mixnode, for example 1.1.1.1 or foo.mixnode.com
   */
  host: string;
  /**
   * Port used by this mixnode for listening for mix packets.
   */
  mix_port: number;
  /**
   * Port used by this mixnode for listening for verloc requests.
   */
  verloc_port: number;
  /**
   * Port used by this mixnode for its http(s) API
   */
  http_api_port: number;
  /**
   * Base58-encoded x25519 public key used for sphinx key derivation.
   */
  sphinx_key: string;
  /**
   * Base58-encoded ed25519 EdDSA public key.
   */
  identity_key: string;
  /**
   * The self-reported semver version of this mixnode.
   */
  version: string;
};
