// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeConfigUpdate = {
  host: string | null;
  custom_http_port: number | null;
  restore_default_http_port: boolean;
};
