// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeRewarding } from './NodeRewarding';
import type { NymNodeBond } from './NymNodeBond';
import type { PendingNodeChanges } from './PendingNodeChanges';

/**
 * Full details associated with given node.
 */
export type NymNodeDetails = {
  /**
   * Basic bond information of this node, such as owner address, original pledge, etc.
   */
  bond_information: NymNodeBond;
  /**
   * Details used for computation of rewarding related data.
   */
  rewarding_details: NodeRewarding;
  /**
   * Adjustments to the node that are scheduled to happen during future epoch/interval transitions.
   */
  pending_changes: PendingNodeChanges;
};
