// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecCoin } from './DecCoin';

export type NymNodeBond = {
  /**
   * Unique id assigned to the bonded node.
   */
  node_id: number;
  /**
   * Address of the owner of this nym-node.
   */
  owner: string;
  /**
   * Original amount pledged by the operator of this node.
   */
  original_pledge: DecCoin;
  /**
   * Block height at which this nym-node has been bonded.
   */
  bonding_height: bigint;
  /**
   * Flag to indicate whether this node is in the process of unbonding,
   * that will conclude upon the epoch finishing.
   */
  is_unbonding: boolean;
  /**
   * Network address of this nym-node, for example 1.1.1.1 or foo.mixnode.com
   * that is used to discover other capabilities of this node.
   */
  host: string;
  /**
   * Allow specifying custom port for accessing the http, and thus self-described, api
   * of this node for the capabilities discovery.
   */
  custom_http_port: number | null;
  /**
   * Base58-encoded ed25519 EdDSA public key.
   */
  identity_key: string;
};
