// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PendingNodeChanges = { pledge_change: number | null; cost_params_change: number | null };
