// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingFamilyInvitationDetails } from "./PendingFamilyInvitationDetails";

/**
 * Response to [`QueryMsg::GetPendingInvitationsForFamilyPaged`](crate::QueryMsg::GetPendingInvitationsForFamilyPaged).
 */
export type PendingFamilyInvitationsPagedResponse = { 
/**
 * The family whose pending invitations were queried, echoed back so
 * paginated callers can correlate.
 */
family_id: number, 
/**
 * The pending invitations on this page, in ascending invitee
 * [`NodeId`] order, each stamped with whether it had already timed out
 * at the time the query was served.
 */
invitations: Array<PendingFamilyInvitationDetails>, 
/**
 * Cursor (last invitee node id) to pass as `start_after` on the next
 * call, or `None` if this page is empty (treat as end-of-list).
 */
start_next_after: number | null, };
