// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingFamilyInvitationDetails } from "./PendingFamilyInvitationDetails";

/**
 * Response to [`QueryMsg::GetPendingInvitationsForNodePaged`](crate::QueryMsg::GetPendingInvitationsForNodePaged).
 */
export type PendingInvitationsForNodePagedResponse = { 
/**
 * The node whose pending invitations were queried, echoed back so
 * paginated callers can correlate.
 */
node_id: number, 
/**
 * The pending invitations addressed to this node on this page, in
 * ascending [`NodeFamilyId`] order, each stamped with whether it had
 * already timed out at the time the query was served.
 */
invitations: Array<PendingFamilyInvitationDetails>, 
/**
 * Cursor (last issuing family id) to pass as `start_after` on the
 * next call, or `None` if this page is empty (treat as end-of-list).
 */
start_next_after: number | null, };
