// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntervalRewardingParamsUpdate } from './IntervalRewardingParamsUpdate';
import type { MixNodeCostParams } from './MixNodeCostParams';

export type PendingIntervalEventData =
  | { ChangeMixCostParams: { mix_id: number; new_costs: MixNodeCostParams } }
  | { UpdateRewardingParams: { update: IntervalRewardingParamsUpdate } }
  | { UpdateIntervalConfig: { epochs_in_interval: number; epoch_duration_secs: bigint } };
