// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingIntervalEventData } from './PendingIntervalEventData';

export type PendingIntervalEvent = { id: number; created_at: bigint; event: PendingIntervalEventData };
