// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingEpochEventData } from './PendingEpochEventData';

export type PendingEpochEvent = { id: number; created_at: bigint; event: PendingEpochEventData };
