// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntervalRewardParams } from './IntervalRewardParams';
import type { RewardedSetParams } from './RewardedSetParams';

/**
 * Parameters used for reward calculation.
 */
export type RewardingParams = {
  /**
   * Parameters that should remain unchanged throughout an interval.
   */
  interval: IntervalRewardParams;
  rewarded_set: RewardedSetParams;
};
