// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RewardEstimate {
  total_node_reward: string;
  operator: string;
  delegates: string;
  operating_cost: string;
}
