// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Interval } from './Interval';
import type { RewardEstimate } from './RewardEstimate';
import type { RewardingParams } from './RewardingParams';

export type RewardEstimationResponse = {
  estimation: RewardEstimate;
  reward_params: RewardingParams;
  epoch: Interval;
  as_at: number;
};
