// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecCoin } from './DecCoin';

export type TransactionDetails = { amount: DecCoin; from_address: string; to_address: string };
