// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecCoin } from './DecCoin';
import type { GasInfo } from './GasInfo';

export interface TransactionExecuteResult {
  logs_json: string;
  msg_responses_json: string;
  transaction_hash: string;
  gas_info: GasInfo;
  fee: DecCoin | null;
}
