// Copyright 2026 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: Apache-2.0

//! Compiled-in directory light-client checkpoint: the `SignedCheckpoint` datum, JSON-encoded,
//! embedded from the sibling `directory_checkpoint.json` data file.
//!
//! Only the data file is (re)generated by the offline checkpoint minting tool (see the
//! `directory-checkpoint-bootstrap` change); this wrapper never changes. An empty data file means
//! "no compiled checkpoint" - the hardcoded checkpoint provider treats it as absent and the loader
//! falls through to its other sources. It stays empty until the real mainnet checkpoint is minted.

pub const DIRECTORY_CHECKPOINT: &str = include_str!("directory_checkpoint.json");
