# Like makefile but in Rust, and possibly simpler / more powerful
# https://github.com/casey/just#quick-start

upload: code_id

wasm:
	RUSTFLAGS='-C link-arg=-s' cargo build --release --target wasm32-unknown-unknown

code_id: wasm
	validator-client-scripts --nymd-url ${QA_NYMD_URL} --mnemonic "${QA_MNEMONIC}" --contract ${QA_CONTRACT} upload --wasm-path target/wasm32-unknown-unknown/release/mixnet_contracts.wasm > code_id

migrate: upload
	cat code_id | xargs -I {} validator-client-scripts --nymd-url ${QA_NYMD_URL} --mnemonic "${QA_MNEMONIC}" --contract ${QA_CONTRACT}  migrate --code-id {}

init: upload
	cat code_id | xargs -I {} validator-client-scripts --nymd-url ${QA_NYMD_URL} --mnemonic "${QA_MNEMONIC}" --contract ${QA_CONTRACT}  init --code-id {}

clean:
	cargo clean
	rm -f code_id

