#ifndef CONSTS_NAMESPACE_H
#define CONSTS_NAMESPACE_H

#define hh_p1 CRYPTO_SHARED_NAMESPACE(hh_p1)
#define hh_p2 CRYPTO_SHARED_NAMESPACE(hh_p2)
#define hh_p3 CRYPTO_SHARED_NAMESPACE(hh_p3)
#define sub_p1 CRYPTO_SHARED_NAMESPACE(sub_p1)
#define sub_p2 CRYPTO_SHARED_NAMESPACE(sub_p2)
#define sub_p3 CRYPTO_SHARED_NAMESPACE(sub_p3)
#define hh_xor CRYPTO_SHARED_NAMESPACE(hh_xor)
#define swap_c CRYPTO_SHARED_NAMESPACE(swap_c)
#define swap_mask CRYPTO_SHARED_NAMESPACE(swap_mask)
#define vec19 CRYPTO_SHARED_NAMESPACE(vec19)
#define vec608 CRYPTO_SHARED_NAMESPACE(vec608)
#define vecmask52 CRYPTO_SHARED_NAMESPACE(vecmask52)
#define vecmask47 CRYPTO_SHARED_NAMESPACE(vecmask47)
#define a24 CRYPTO_SHARED_NAMESPACE(a24)
#define mask63 CRYPTO_SHARED_NAMESPACE(mask63)

#endif //ifndef CONSTS_NAMESPACE_H

