// Copyright 2024 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: Apache-2.0

#![allow(unknown_lints)]
// clippy::empty_docs is not on stable as of 1.77

// due to the code generated by Tsify
#![allow(clippy::empty_docs)]

use wasm_bindgen::prelude::*;

pub mod bandwidth_voucher;
pub mod error;
pub mod generic_scheme;
pub(crate) mod helpers;
pub mod ticketbook;
pub mod types;

// keep in internal to the crate since I'm not sure how temporary this thing is going to be
// I mostly got it, so I could test the whole thing end to end
pub(crate) mod vpn_api_client;

#[wasm_bindgen(start)]
// #[cfg(target_arch = "wasm32")]
pub fn main() {
    nym_wasm_utils::console_log!("[rust main]: rust module loaded");
    nym_wasm_utils::console_log!(
        "wasm zk-nym version used: {}",
        nym_bin_common::bin_info_owned!()
    );
}
