pub const PUBLIC_ATTRIBUTES_LEN: usize = 1;
pub const PRIVATE_ATTRIBUTES_LEN: usize = 2;
pub const ATTRIBUTES_LEN: usize = 3; // number of attributes encoded in a single zk-nym credential
pub const CRED_VALIDITY_PERIOD: u64 = 30;
pub const FREEPASS_VALIDITY_PERIOD: u64 = 7;
pub const NB_TICKETS: u64 = 1000;
pub const SPEND_TICKETS: u64 = 1;
pub const TYPE_EXP: [u8; 32] = *b"ZKNYMEXPIRATIONDATE4llCBMEypAxr3";
pub const TYPE_IDX: [u8; 32] = *b"ZKNYMSINDICESh^7gTYbhnap*12n5GG6";
