// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/nymtech/nym-directory/models"
	mock "github.com/stretchr/testify/mock"
)

// CocoHostSanitizer is an autogenerated mock type for the CocoHostSanitizer type
type CocoHostSanitizer struct {
	mock.Mock
}

// Sanitize provides a mock function with given fields: _a0
func (_m *CocoHostSanitizer) Sanitize(_a0 models.CocoHostInfo) models.CocoHostInfo {
	ret := _m.Called(_a0)

	var r0 models.CocoHostInfo
	if rf, ok := ret.Get(0).(func(models.CocoHostInfo) models.CocoHostInfo); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.CocoHostInfo)
	}

	return r0
}
