// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// AddCocoNodePresence provides a mock function with given fields: c
func (_m *Controller) AddCocoNodePresence(c *gin.Context) {
	_m.Called(c)
}

// AddMixNodePresence provides a mock function with given fields: c
func (_m *Controller) AddMixNodePresence(c *gin.Context) {
	_m.Called(c)
}

// RegisterRoutes provides a mock function with given fields: router
func (_m *Controller) RegisterRoutes(router *gin.Engine) {
	_m.Called(router)
}

// Topology provides a mock function with given fields: c
func (_m *Controller) Topology(c *gin.Context) {
	_m.Called(c)
}
