// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPAssigner is an autogenerated mock type for the IPAssigner type
type IPAssigner struct {
	mock.Mock
}

// AssignIP provides a mock function with given fields: serverReportedIP, selfReportedHost
func (_m *IPAssigner) AssignIP(serverReportedIP string, selfReportedHost string) (string, error) {
	ret := _m.Called(serverReportedIP, selfReportedHost)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(serverReportedIP, selfReportedHost)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(serverReportedIP, selfReportedHost)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
