/* automatically generated by rust-bindgen 0.64.0 */

extern "C" {
    pub static mut cpucycles:
        ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_longlong>;
}
extern "C" {
    pub fn cpucycles_implementation() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn cpucycles_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn cpucycles_persecond() -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn cpucycles_tracesetup();
}
