export const config = {
    NYMD_URL: process.env.NYMD_URL as string,
    VALIDATOR_API: process.env.VALIDATOR_API as string,
    MIXNET_CONTRACT: process.env.MIXNET_CONTRACT as string,
    VESTING_CONTRACT: process.env.VESTING_CONTRACT as string,
    USER_MNEMONIC: process.env.USER_MNEMONIC as string,
    USER_WALLET_ADDRESS: process.env.USER_WALLET_ADDRESS as string,
    CURRENCY_PREFIX: process.env.CURRENCY_PREFIX as string,
    CHAIN_ID: process.env.CHAIN_ID as string,
    MIXNODE_IDENTITY: process.env.MIXNODE_IDENTITY as string,
    MIXNODE_SPHINX_KEY: process.env.MIXNODE_SPHINX_KEY as string,
    MIXNODE_SIGNATURE: process.env.MIXNODE_SIGNATURE as string,
    MIXNODE_HOST: process.env.MIXNODE_HOST as string,
    MIXNODE_VERSION: process.env.MIXNODE_VERSION as string,
    GATEWAY_IDENTITY: process.env.GATEWAY_IDENTITY as string,
    GATEWAY_SIGNATURE: process.env.GATEWAY_SIGNATURE as string,
    GATEWAY_SPHINX: process.env.GATEWAY_SPHINX as string,
    GATEWAY_LOCATION: process.env.GATEWAY_LOCATION as string,
    GATEWAY_HOST: process.env.GATEWAY_HOST as string,
    GATEWAY_VERSION: process.env.GATEWAY_VERSION as string,
}
