[package]
name = "nym-serde-helpers"
description = "Serde helpers for hex/base64/base58/datetime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true
readme.workspace = true
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_with = { workspace = true, optional = true }
time = { workspace = true, features = ["formatting", "parsing", "macros"], optional = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[features]
hex = ["serde_with/hex"]
bs58 = ["serde_with/base58"]
base64 = ["serde_with/base64"]
date = ["time"]
