// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FamilyMembership } from "./FamilyMembership";

/**
 * One entry in a [`FamilyMembersPagedResponse`] page — pairs a node id with
 * its [`FamilyMembership`] record (notably its `joined_at` timestamp).
 */
export type FamilyMemberRecord = { 
/**
 * The node currently in the family.
 */
node_id: number, 
/**
 * The membership record (carries `family_id` and `joined_at`).
 */
membership: FamilyMembership, };
