// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * On-chain record of a node's current family membership.
 *
 * A node belongs to at most one family at a time, so this is keyed by
 * `NodeId` alone — `family_id` is carried in the value to support reverse
 * lookups (all nodes in a given family) via a secondary index.
 */
export type FamilyMembership = { 
/**
 * The family the node is currently a member of.
 */
family_id: number, 
/**
 * Block timestamp (unix seconds) at which the node accepted its
 * invitation and joined the family.
 */
joined_at: number, };
