// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeFamily } from "./NodeFamily";

/**
 * Response to [`QueryMsg::GetFamilyById`](crate::QueryMsg::GetFamilyById).
 */
export type NodeFamilyResponse = { 
/**
 * The id that was queried, echoed back so paginated callers can correlate.
 */
family_id: number, 
/**
 * The matching family, or `None` if no family with `family_id` exists.
 */
family: NodeFamily | null, };
