// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeFamily } from "./NodeFamily";

/**
 * Response to [`QueryMsg::GetFamilyByOwner`](crate::QueryMsg::GetFamilyByOwner).
 */
export type NodeFamilyByOwnerResponse = { 
/**
 * The (validated) owner address that was queried, echoed back so callers
 * can correlate.
 */
owner: string, 
/**
 * The matching family, or `None` if `owner` does not currently own one.
 */
family: NodeFamily | null, };
