// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PastFamilyInvitation } from "./PastFamilyInvitation";

/**
 * Response to [`QueryMsg::GetPastInvitationsForFamilyPaged`](crate::QueryMsg::GetPastInvitationsForFamilyPaged).
 */
export type PastFamilyInvitationsPagedResponse = { 
/**
 * The family whose archived invitations were queried, echoed back so
 * paginated callers can correlate.
 */
family_id: number, 
/**
 * The archived invitations on this page, in ascending
 * `(node_id, counter)` order across all terminal statuses.
 */
invitations: Array<PastFamilyInvitation>, 
/**
 * Cursor to pass as `start_after` on the next call, or `None` if this
 * page is empty (treat as end-of-list).
 */
start_next_after: [number, number] | null, };
