// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingFamilyInvitationDetails } from "./PendingFamilyInvitationDetails";

/**
 * Response to [`QueryMsg::GetPendingInvitation`](crate::QueryMsg::GetPendingInvitation).
 */
export type PendingFamilyInvitationResponse = { 
/**
 * The family component of the queried `(family_id, node_id)` key.
 */
family_id: number, 
/**
 * The node component of the queried `(family_id, node_id)` key.
 */
node_id: number, 
/**
 * The matching pending invitation along with an explicit expiry flag,
 * or `None` if no such invitation exists.
 */
invitation: PendingFamilyInvitationDetails | null, };
