// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FamilyInvitation } from "./FamilyInvitation";

/**
 * A pending [`FamilyInvitation`] paired with whether it has already timed
 * out at the time the query was served.
 */
export type PendingFamilyInvitationDetails = { 
/**
 * The stored invitation as it was issued.
 */
invitation: FamilyInvitation, 
/**
 * `true` iff `now >= invitation.expires_at` at query time, i.e. the
 * invitation is still in the pending map but can no longer be acted on.
 */
expired: boolean, };
