// Copyright 2026 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: Apache-2.0

//! smoltcp `Device` implementation backed by in-memory VecDeque buffers.
//!
//! The native smolmix uses `NymAsyncDevice` (Stream/Sink over mpsc channels) fed
//! into `tokio-smoltcp`. On wasm32 we drive smoltcp directly, so we need a sync
//! `Device` impl instead. The bridge pushes incoming IP packets into `rx_queue`
//! and pops outgoing packets from `tx_queue`.

use std::collections::{BTreeSet, VecDeque};

use smoltcp::phy::{Device, DeviceCapabilities, Medium, RxToken, TxToken};
use smoltcp::time::Instant;
use smoltcp::wire::{IpAddress, IpProtocol, Ipv4Address, Ipv4Packet, TcpPacket};
use std::collections::BTreeMap;

/// smoltcp device backed by in-memory packet queues.
///
/// The bridge task feeds incoming IP packets via [`push_rx`](Self::push_rx) and
/// drains outgoing packets via [`drain_tx`](Self::drain_tx). The reactor calls
/// smoltcp's `Interface::poll()` which invokes the `Device` trait methods.
pub struct WasmDevice {
    rx_queue: VecDeque<Vec<u8>>,
    tx_queue: VecDeque<Vec<u8>>,
    capabilities: DeviceCapabilities,
    rx_stats: RxStats,
    tx_stats: TxStats,
}

/// Client MTU: Android keeps its mobile MTU (1280); elsewhere use the IPR-reported
/// MTU (v10) or 1420 for pre-v10 IPRs.
fn client_mtu(negotiated: Option<u16>) -> usize {
    #[cfg(target_arch = "wasm32")]
    {
        if is_android() {
            return usize::from(nym_ip_packet_requests::CLIENT_MTU_MOBILE);
        }
    }
    usize::from(negotiated.unwrap_or(nym_ip_packet_requests::CLIENT_MTU_FALLBACK))
}

/// Sniff the platform from `navigator.userAgent`. Reads the property off the JS
/// global via reflection so it works in both `Window` and `WorkerGlobalScope`
/// contexts without pulling in extra web-sys features. Falls back to `false` (1420)
/// if the property is missing.
#[cfg(target_arch = "wasm32")]
fn is_android() -> bool {
    use wasm_bindgen::JsValue;
    let global = js_sys::global();
    js_sys::Reflect::get(&global, &JsValue::from_str("navigator"))
        .ok()
        .and_then(|nav| js_sys::Reflect::get(&nav, &JsValue::from_str("userAgent")).ok())
        .and_then(|ua| ua.as_string())
        .map(|ua| ua.to_ascii_lowercase().contains("android"))
        .unwrap_or(false)
}

impl WasmDevice {
    pub fn new(negotiated_mtu: Option<u16>) -> Self {
        let mut capabilities = DeviceCapabilities::default();
        capabilities.medium = Medium::Ip;
        // See client_mtu for the per-platform MTU choice.
        capabilities.max_transmission_unit = client_mtu(negotiated_mtu);
        // Native smolmix also uses Some(1) in the device, but tokio-smoltcp
        // compensates with a burst loop that calls Interface::poll() up to 100
        // times per reactor iteration (each processing 1 packet). Our WASM
        // reactor only calls poll() once per tick, so we set a higher burst
        // size to let smoltcp drain all pending packets in a single poll().
        capabilities.max_burst_size = Some(100);

        Self {
            rx_queue: VecDeque::new(),
            tx_queue: VecDeque::new(),
            capabilities,
            rx_stats: RxStats::default(),
            tx_stats: TxStats::default(),
        }
    }

    /// Push an incoming IP packet (from the mixnet) into the receive queue.
    pub fn push_rx(&mut self, packet: Vec<u8>) {
        // Aggregate diagnostic (replaces the former per-packet log). Only folds
        // when runtime debug logging is on, so the production path stays a bare
        // enqueue: one atomic load, no parsing. The window is flushed on a
        // connection lifecycle flag or when it fills; see `RxStats`.
        if nym_wasm_utils::debug_logging_enabled() {
            if let Some(pkt) = parse_inbound_tcp(&packet) {
                let lifecycle = pkt.syn || pkt.rst || pkt.fin;
                self.rx_stats.record(&pkt);
                if lifecycle || self.rx_stats.segments >= RX_STATS_WINDOW {
                    self.rx_stats.flush();
                }
            }
        }
        self.rx_queue.push_back(packet);
    }

    /// Drain all outgoing IP packets (generated by smoltcp) from the transmit queue.
    pub fn drain_tx(&mut self) -> impl Iterator<Item = Vec<u8>> + '_ {
        self.tx_queue.drain(..)
    }
}

impl Device for WasmDevice {
    type RxToken<'a> = WasmRxToken;
    type TxToken<'a> = WasmTxToken<'a>;

    fn receive(&mut self, _timestamp: Instant) -> Option<(Self::RxToken<'_>, Self::TxToken<'_>)> {
        let packet = self.rx_queue.pop_front()?;
        Some((
            WasmRxToken { buffer: packet },
            WasmTxToken {
                queue: &mut self.tx_queue,
                stats: &mut self.tx_stats,
            },
        ))
    }

    fn transmit(&mut self, _timestamp: Instant) -> Option<Self::TxToken<'_>> {
        Some(WasmTxToken {
            queue: &mut self.tx_queue,
            stats: &mut self.tx_stats,
        })
    }

    fn capabilities(&self) -> DeviceCapabilities {
        self.capabilities.clone()
    }
}

/// Receive token: delivers one packet from the rx queue to smoltcp.
pub struct WasmRxToken {
    buffer: Vec<u8>,
}

impl RxToken for WasmRxToken {
    fn consume<R, F>(self, f: F) -> R
    where
        F: FnOnce(&[u8]) -> R,
    {
        f(&self.buffer)
    }
}

/// Flush the rx aggregate after this many segments even when no lifecycle flag
/// has appeared, so a long bulk transfer still reports periodically rather than
/// only at teardown.
const RX_STATS_WINDOW: u32 = 256;

/// Fields aggregated from one inbound TCP packet.
struct InboundTcp {
    /// Our local ephemeral port: which client socket this belongs to. It is the
    /// discriminator for "one connection or several?". Each tcp_connect (and
    /// each connect retry) uses a fresh port, so a window touching several
    /// dports means several of our own connections, not one flow.
    dport: u16,
    payload_len: usize,
    cksum_ok: bool,
    syn: bool,
    rst: bool,
    fin: bool,
}

/// Parse the fields we aggregate from one inbound packet. IPv4/TCP only:
/// IPv6 and non-TCP return `None` and are simply not counted. A bad checksum
/// is recorded (`cksum_ok = false`), not dropped, since seeing it is the point.
fn parse_inbound_tcp(buf: &[u8]) -> Option<InboundTcp> {
    let ip = Ipv4Packet::new_checked(buf).ok()?;
    let ip_ok = ip.verify_checksum();
    if ip.next_header() != IpProtocol::Tcp {
        return None;
    }
    let src = IpAddress::Ipv4(ip.src_addr());
    let dst = IpAddress::Ipv4(ip.dst_addr());
    let tcp = TcpPacket::new_checked(ip.payload()).ok()?;
    Some(InboundTcp {
        dport: tcp.dst_port(),
        payload_len: tcp.payload().len(),
        cksum_ok: ip_ok && tcp.verify_checksum(&src, &dst),
        syn: tcp.syn(),
        rst: tcp.rst(),
        fin: tcp.fin(),
    })
}

/// Rolling aggregate of inbound TCP packets, flushed to the debug log on a
/// connection lifecycle flag (SYN/RST/FIN) or when [`RX_STATS_WINDOW`] segments
/// accumulate. Replaces the former per-packet firehose: it keeps the same
/// investigative signal (segment and byte counts, checksum failures, how many
/// distinct local ports, ie how many connections, and the handshake/teardown
/// flags) without a line per packet.
///
/// Only touched when runtime debug logging is on. A *silent* stall (the flight
/// just stops, no RST) won't flush, since the device has no timer; the RST that
/// usually ends a stalled flight over the mixnet does trigger a flush.
#[derive(Default)]
struct RxStats {
    segments: u32,
    bytes: usize,
    bad_cksum: u32,
    syn: u32,
    rst: u32,
    fin: u32,
    dports: BTreeSet<u16>,
}

impl RxStats {
    /// Fold one parsed inbound packet into the current window.
    fn record(&mut self, pkt: &InboundTcp) {
        self.segments += 1;
        self.bytes += pkt.payload_len;
        if !pkt.cksum_ok {
            self.bad_cksum += 1;
        }
        self.syn += u32::from(pkt.syn);
        self.rst += u32::from(pkt.rst);
        self.fin += u32::from(pkt.fin);
        self.dports.insert(pkt.dport);
    }

    /// Emit the window summary and reset. No-op on an empty window.
    ///
    /// How to read a line:
    ///   seg          inbound TCP segments in this window
    ///   payload bytes total TCP payload across those segments (no headers); a
    ///                climbing total with no completion means a stalled flight
    ///   bad cksum    segments that failed IP or TCP checksum; should stay 0.
    ///                Nonzero means corruption on the path, not just loss
    ///   dports       distinct local ports touched, ie how many of our own
    ///                connections this window spans (retries open fresh ports)
    ///   S / R / F    SYN / RST / FIN counts. R>0 is the handshake-era failure
    ///                signature (connection reset); a clean flow is S then F,
    ///                R=0 throughout
    fn flush(&mut self) {
        if self.segments == 0 {
            return;
        }
        crate::util::debug_log!(
            "[device] rx window: {} seg, {} payload bytes, {} bad cksum, {} dports, S={} R={} F={}",
            self.segments,
            self.bytes,
            self.bad_cksum,
            self.dports.len(),
            self.syn,
            self.rst,
            self.fin,
        );
        *self = RxStats::default();
    }
}

/// Flush the tx aggregate after this many segments, mirroring the rx window.
const TX_STATS_WINDOW: u32 = 256;

/// Fields aggregated from one outbound TCP packet.
struct OutboundTcp {
    /// Our local ephemeral port: smoltcp keeps it stable for a connection's
    /// life, so it identifies the flow. This is the field an IPR egress capture
    /// is correlated against (the exit's NAT may remap it on the way out).
    src_port: u16,
    /// (destination address, destination port).
    dst: (Ipv4Address, u16),
    payload_len: usize,
    syn: bool,
    rst: bool,
    fin: bool,
}

/// Parse the fields we aggregate from one outbound packet. IPv4/TCP only.
/// No checksum check: smoltcp fills those in after we observe the packet.
fn parse_outbound_tcp(buf: &[u8]) -> Option<OutboundTcp> {
    let ip = Ipv4Packet::new_checked(buf).ok()?;
    if ip.next_header() != IpProtocol::Tcp {
        return None;
    }
    let tcp = TcpPacket::new_checked(ip.payload()).ok()?;
    Some(OutboundTcp {
        src_port: tcp.src_port(),
        dst: (ip.dst_addr(), tcp.dst_port()),
        payload_len: tcp.payload().len(),
        syn: tcp.syn(),
        rst: tcp.rst(),
        fin: tcp.fin(),
    })
}

/// Rolling aggregate of outbound TCP packets, flushed on a connection lifecycle
/// flag (SYN/RST/FIN) or when [`TX_STATS_WINDOW`] segments accumulate. Replaces
/// the former per-packet tx log.
///
/// The outbound diagnostic is about source-port stability: each flow's
/// `src_port -> dst` mapping is the data an egress capture is correlated
/// against. smoltcp keeps that port stable for us, so this stays quiet, listing
/// the flows seen each window. `port_reuses` counts a `src_port` re-pointing at
/// a different dst within one window: usually a legitimate fast close-and-reopen
/// reusing the port, but a sustained nonzero count is worth a look (the port
/// allocator handing out a still-live port).
///
/// Only touched when runtime debug logging is on.
#[derive(Default)]
struct TxStats {
    segments: u32,
    bytes: usize,
    syn: u32,
    rst: u32,
    fin: u32,
    /// `src_port -> dst` seen this window: the correlation mapping, and the
    /// basis for the reuse check.
    flows: BTreeMap<u16, (Ipv4Address, u16)>,
    port_reuses: u32,
}

impl TxStats {
    /// Fold one parsed outbound packet into the current window.
    fn record(&mut self, pkt: &OutboundTcp) {
        self.segments += 1;
        self.bytes += pkt.payload_len;
        self.syn += u32::from(pkt.syn);
        self.rst += u32::from(pkt.rst);
        self.fin += u32::from(pkt.fin);
        if let Some(prev) = self.flows.insert(pkt.src_port, pkt.dst) {
            if prev != pkt.dst {
                self.port_reuses += 1;
            }
        }
    }

    /// Emit the window summary and reset. No-op on an empty window.
    ///
    ///   seg / bytes   outbound segments and total payload this window
    ///   flows         `src_port->dst` per flow, for egress-capture correlation
    ///   port-reuse    a src_port re-pointed at a new dst mid-window (see above)
    ///   S / R / F     SYN / RST / FIN counts we sent
    fn flush(&mut self) {
        if self.segments == 0 {
            return;
        }
        let flows: Vec<String> = self
            .flows
            .iter()
            .map(|(sport, (ip, dport))| format!("{sport}->{ip}:{dport}"))
            .collect();
        crate::util::debug_log!(
            "[device] tx window: {} seg, {} payload bytes, {} flows [{}], {} port-reuse, S={} R={} F={}",
            self.segments,
            self.bytes,
            self.flows.len(),
            flows.join(" "),
            self.port_reuses,
            self.syn,
            self.rst,
            self.fin,
        );
        *self = TxStats::default();
    }
}

/// Transmit token: captures one packet from smoltcp into the tx queue.
pub struct WasmTxToken<'a> {
    queue: &'a mut VecDeque<Vec<u8>>,
    stats: &'a mut TxStats,
}

impl<'a> TxToken for WasmTxToken<'a> {
    fn consume<R, F>(self, len: usize, f: F) -> R
    where
        F: FnOnce(&mut [u8]) -> R,
    {
        let mut buffer = vec![0u8; len];
        let result = f(&mut buffer);
        // Aggregate diagnostic (see TxStats). Only folds when runtime debug
        // logging is on, so the production path stays a bare enqueue.
        if nym_wasm_utils::debug_logging_enabled() {
            if let Some(pkt) = parse_outbound_tcp(&buffer) {
                let lifecycle = pkt.syn || pkt.rst || pkt.fin;
                self.stats.record(&pkt);
                if lifecycle || self.stats.segments >= TX_STATS_WINDOW {
                    self.stats.flush();
                }
            }
        }
        self.queue.push_back(buffer);
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn push_rx_and_receive() {
        let mut dev = WasmDevice::new(None);
        dev.push_rx(vec![1, 2, 3]);

        let now = Instant::from_millis(0);
        let (rx, _tx) = dev.receive(now).expect("should have a packet");
        let data = rx.consume(|buf| buf.to_vec());
        assert_eq!(data, vec![1, 2, 3]);
    }

    #[test]
    fn transmit_and_drain() {
        let mut dev = WasmDevice::new(None);
        let now = Instant::from_millis(0);

        let tx = dev.transmit(now).expect("should get tx token");
        tx.consume(4, |buf| {
            buf.copy_from_slice(&[0xDE, 0xAD, 0xBE, 0xEF]);
        });

        let packets: Vec<_> = dev.drain_tx().collect();
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0], vec![0xDE, 0xAD, 0xBE, 0xEF]);
    }

    #[test]
    fn empty_receive_returns_none() {
        let mut dev = WasmDevice::new(None);
        assert!(dev.receive(Instant::from_millis(0)).is_none());
    }

    #[test]
    fn capabilities_are_ip_mode() {
        let dev = WasmDevice::new(None);
        let caps = dev.capabilities();
        assert_eq!(caps.medium, Medium::Ip);
        // Native target: the Android sniff is wasm-only, so client_mtu(None) is always the 1420 fallback.
        assert_eq!(caps.max_transmission_unit, 1420);
    }
}
