// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/nymtech/nym-directory/models"

// IService is an autogenerated mock type for the IService type
type IService struct {
	mock.Mock
}

// CreateMixMetric provides a mock function with given fields: metric
func (_m *IService) CreateMixMetric(metric models.MixMetric) {
	_m.Called(metric)
}

// List provides a mock function with given fields:
func (_m *IService) List() []models.PersistedMixMetric {
	ret := _m.Called()

	var r0 []models.PersistedMixMetric
	if rf, ok := ret.Get(0).(func() []models.PersistedMixMetric); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PersistedMixMetric)
		}
	}

	return r0
}
