#ifndef CONSTS_NAMESPACE_H
#define CONSTS_NAMESPACE_H

#define vec19 CRYPTO_SHARED_NAMESPACE(vec19)
#define vecmask25 CRYPTO_SHARED_NAMESPACE(vecmask25)
#define vecmask26 CRYPTO_SHARED_NAMESPACE(vecmask26)
#define pmask1 CRYPTO_SHARED_NAMESPACE(pmask1)
#define pmask2 CRYPTO_SHARED_NAMESPACE(pmask2)
#define pmask3 CRYPTO_SHARED_NAMESPACE(pmask3)
#define pmask4 CRYPTO_SHARED_NAMESPACE(pmask4)
#define pmask5 CRYPTO_SHARED_NAMESPACE(pmask5)
#define pmask6 CRYPTO_SHARED_NAMESPACE(pmask6)
#define pmask7 CRYPTO_SHARED_NAMESPACE(pmask7)
#define pmask8 CRYPTO_SHARED_NAMESPACE(pmask8)
#define pmask9 CRYPTO_SHARED_NAMESPACE(pmask9)
#define pmask10 CRYPTO_SHARED_NAMESPACE(pmask10)
#define pmask11 CRYPTO_SHARED_NAMESPACE(pmask11)
#define pmask12 CRYPTO_SHARED_NAMESPACE(pmask12)
#define upmask1 CRYPTO_SHARED_NAMESPACE(upmask1)
#define upmask2 CRYPTO_SHARED_NAMESPACE(upmask2)
#define upmask3 CRYPTO_SHARED_NAMESPACE(upmask3)
#define upmask4 CRYPTO_SHARED_NAMESPACE(upmask4)
#define upmask5 CRYPTO_SHARED_NAMESPACE(upmask5)
#define mask63 CRYPTO_SHARED_NAMESPACE(mask63)
#define EC2D0 CRYPTO_SHARED_NAMESPACE(EC2D0)
#define EC2D1 CRYPTO_SHARED_NAMESPACE(EC2D1)
#define EC2D2 CRYPTO_SHARED_NAMESPACE(EC2D2)
#define EC2D3 CRYPTO_SHARED_NAMESPACE(EC2D3)

#endif //ifndef CONSTS_NAMESPACE_H

