#ifndef CONSTS_NAMESPACE_H
#define CONSTS_NAMESPACE_H

#define hh_p1 CRYPTO_SHARED_NAMESPACE(hh_p1)
#define hh_p2 CRYPTO_SHARED_NAMESPACE(hh_p2)
#define hh_p3 CRYPTO_SHARED_NAMESPACE(hh_p3)
#define hh_xor CRYPTO_SHARED_NAMESPACE(hh_xor)
#define sub_p1 CRYPTO_SHARED_NAMESPACE(sub_p1)
#define sub_p2 CRYPTO_SHARED_NAMESPACE(sub_p2)
#define sub_p3 CRYPTO_SHARED_NAMESPACE(sub_p3)
#define swap_c CRYPTO_SHARED_NAMESPACE(swap_c)
#define swap_mask CRYPTO_SHARED_NAMESPACE(swap_mask)
#define sh2526 CRYPTO_SHARED_NAMESPACE(sh2526)
#define sh2625 CRYPTO_SHARED_NAMESPACE(sh2625)
#define vec19 CRYPTO_SHARED_NAMESPACE(vec19)
#define vec38 CRYPTO_SHARED_NAMESPACE(vec38)
#define vecmask25 CRYPTO_SHARED_NAMESPACE(vecmask25)
#define vecmask26 CRYPTO_SHARED_NAMESPACE(vecmask26)
#define vecmask32 CRYPTO_SHARED_NAMESPACE(vecmask32)
#define vecmask2526 CRYPTO_SHARED_NAMESPACE(vecmask2526)
#define vecmask2625 CRYPTO_SHARED_NAMESPACE(vecmask2625)
#define mask51 CRYPTO_SHARED_NAMESPACE(mask51)

#endif //ifndef CONSTS_NAMESPACE_H

