// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecCoin } from "./DecCoin";
import type { Fee } from "./Fee";

export type FeeDetails = { amount: DecCoin | null, fee: Fee, };
