// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecCoin } from '../../../../ts-packages/types/src/types/rust/DecCoin';

export type TauriOperatingCostRange = { minimum: DecCoin; maximum: DecCoin };
