/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Ecash.types";
import * as _1 from "./Ecash.client";
import * as _2 from "./CoconutDkg.types";
import * as _3 from "./CoconutDkg.client";
import * as _4 from "./Mixnet.types";
import * as _5 from "./Mixnet.client";
import * as _6 from "./Cw3FlexMultisig.types";
import * as _7 from "./Cw3FlexMultisig.client";
import * as _8 from "./Cw4Group.types";
import * as _9 from "./Cw4Group.client";
import * as _10 from "./Vesting.types";
import * as _11 from "./Vesting.client";
import * as _12 from "./baseClient";
export namespace contracts {
  export const Ecash = {
    ..._0,
    ..._1
  };
  export const CoconutDkg = {
    ..._2,
    ..._3
  };
  export const Mixnet = {
    ..._4,
    ..._5
  };
  export const Cw3FlexMultisig = {
    ..._6,
    ..._7
  };
  export const Cw4Group = {
    ..._8,
    ..._9
  };
  export const Vesting = {
    ..._10,
    ..._11
  };
  export const baseClient = {
    ..._12
  };
}