// Copyright 2026 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: GPL-3.0-only

/// Environment variable names used as fallbacks for CLI arguments.
/// Each constant matches the `env = ...` attribute on the corresponding clap field.
pub mod vars {
    // run orchestrator args
    pub const NYM_NETWORK_MONITOR_ORCHESTRATOR_AGENTS_TOKEN_ARG: &str =
        "NYM_NETWORK_MONITOR_ORCHESTRATOR_AGENTS_TOKEN";
    pub const NYM_NETWORK_MONITOR_ORCHESTRATOR_METRICS_AND_RESULTS_TOKEN_ARG: &str =
        "NYM_NETWORK_MONITOR_ORCHESTRATOR_METRICS_AND_RESULTS_TOKEN";
    pub const NYM_NETWORK_MONITOR_TEST_INTERVAL_ARG: &str = "NYM_NETWORK_MONITOR_TEST_INTERVAL";
    pub const NYM_NETWORK_MONITOR_TEST_TIMEOUT_ARG: &str = "NYM_NETWORK_MONITOR_TEST_TIMEOUT";
    pub const NYM_NETWORK_MONITOR_LIVENESS_ENABLED_ARG: &str =
        "NYM_NETWORK_MONITOR_LIVENESS_ENABLED";
    pub const NYM_NETWORK_MONITOR_LIVENESS_TEST_INTERVAL_ARG: &str =
        "NYM_NETWORK_MONITOR_LIVENESS_TEST_INTERVAL";
    pub const NYM_NETWORK_MONITOR_LIVENESS_TEST_TIMEOUT_ARG: &str =
        "NYM_NETWORK_MONITOR_LIVENESS_TEST_TIMEOUT";
    pub const NYM_NETWORK_MONITOR_LIVENESS_MIXNODE_WAVE_SIZE_ARG: &str =
        "NYM_NETWORK_MONITOR_LIVENESS_MIXNODE_WAVE_SIZE";
    pub const NYM_NETWORK_MONITOR_LIVENESS_GATEWAY_WAVE_SIZE_ARG: &str =
        "NYM_NETWORK_MONITOR_LIVENESS_GATEWAY_WAVE_SIZE";
    pub const NYM_NETWORK_MONITOR_HTTP_SERVER_BIND_ADDRESS_ARG: &str =
        "NYM_NETWORK_MONITOR_HTTP_SERVER_BIND_ADDRESS";
    pub const NYM_NETWORK_MONITOR_NYM_API_ENDPOINT_ARG: &str =
        "NYM_NETWORK_MONITOR_NYM_API_ENDPOINT";
    pub const NYM_NETWORK_MONITOR_MNEMONIC_ARG: &str = "NYM_NETWORK_MONITOR_MNEMONIC";
    pub const NYM_NETWORK_MONITOR_RPC_URL_ARG: &str = "NYM_NETWORK_MONITOR_RPC_URL";
    pub const NYM_NETWORK_MONITOR_DATABASE_PATH_ARG: &str = "NYM_NETWORK_MONITOR_DATABASE_PATH";
    pub const NYM_NETWORK_MONITOR_PRIVATE_KEY_ARG: &str = "NYM_NETWORK_MONITOR_PRIVATE_KEY";
    pub const NYM_NETWORK_MONITOR_NODE_REFRESH_RATE_ARG: &str =
        "NYM_NETWORK_MONITOR_NODE_REFRESH_RATE";
    pub const NYM_NETWORK_MONITOR_NODE_INFO_QUERY_TIMEOUT_ARG: &str =
        "NYM_NETWORK_MONITOR_NODE_INFO_QUERY_TIMEOUT";
    pub const NYM_NETWORK_MONITOR_NETWORK_MONITORS_CONTRACT_ADDRESS_ARG: &str =
        "NYM_NETWORK_MONITOR_NETWORK_MONITORS_CONTRACT_ADDRESS";
    pub const NYM_NETWORK_MONITOR_MIXNET_CONTRACT_ADDRESS_ARG: &str =
        "NYM_NETWORK_MONITOR_MIXNET_CONTRACT_ADDRESS";
    pub const NYM_NETWORK_MONITOR_TESTRUN_EVICTION_AGE_ARG: &str =
        "NYM_NETWORK_MONITOR_TESTRUN_EVICTION_AGE";
    pub const NYM_NETWORK_MONITOR_CONCURRENT_NODE_QUERIES_ARG: &str =
        "NYM_NETWORK_MONITOR_CONCURRENT_NODE_QUERIES";
    pub const NYM_NETWORK_MONITOR_CHAIN_AUTH_CHECK_MAX_ATTEMPTS_ARG: &str =
        "NYM_NETWORK_MONITOR_CHAIN_AUTH_CHECK_MAX_ATTEMPTS";
    pub const NYM_NETWORK_MONITOR_CHAIN_AUTH_CHECK_RETRY_DELAY_ARG: &str =
        "NYM_NETWORK_MONITOR_CHAIN_AUTH_CHECK_RETRY_DELAY";
    pub const NYM_NETWORK_MONITOR_RESULT_SUBMISSION_INTERVAL_ARG: &str =
        "NYM_NETWORK_MONITOR_RESULT_SUBMISSION_INTERVAL";

    pub const NYM_NETWORK_MONITOR_RESULT_SUBMISSION_BATCH_SIZE_ARG: &str =
        "NYM_NETWORK_MONITOR_RESULT_SUBMISSION_BATCH_SIZE";

    pub const NYM_NETWORK_MONITOR_STRESS_AGGREGATION_WINDOW_ARG: &str =
        "NYM_NETWORK_MONITOR_STRESS_AGGREGATION_WINDOW";
    pub const NYM_NETWORK_MONITOR_LIVENESS_AGGREGATION_WINDOW_ARG: &str =
        "NYM_NETWORK_MONITOR_LIVENESS_AGGREGATION_WINDOW";
    pub const NYM_NETWORK_MONITOR_SAMPLE_RETENTION_ARG: &str =
        "NYM_NETWORK_MONITOR_SAMPLE_RETENTION";

    pub const NYM_NETWORK_MONITOR_CHAIN_CAPABILITY_REFRESH_INTERVAL_ARG: &str =
        "NYM_NETWORK_MONITOR_CHAIN_CAPABILITY_REFRESH_INTERVAL";
    pub const NYM_NETWORK_MONITOR_CHAIN_CAPABILITY_REFRESH_JITTER_ARG: &str =
        "NYM_NETWORK_MONITOR_CHAIN_CAPABILITY_REFRESH_JITTER";
    pub const NYM_NETWORK_MONITOR_CHAIN_CAPABILITY_QUERY_CONCURRENCY_ARG: &str =
        "NYM_NETWORK_MONITOR_CHAIN_CAPABILITY_QUERY_CONCURRENCY";
    pub const NYM_NETWORK_MONITOR_MINIMUM_ON_CHAIN_BALANCE_ARG: &str =
        "NYM_NETWORK_MONITOR_MINIMUM_ON_CHAIN_BALANCE";
}
