// Copyright 2026 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: Apache-2.0

//! Post-Quantum Re-Key Protocol

/// This module implements a stateless post-quantum re-keying protocol in one round-trip.
/// We currently support MlKem768 and XWing.
///
/// This protocol is safe if it runs under a trusted secure channel.
///
/// Bandwidth costs:
/// Request (MlKem768): 1216 bytes
/// Response (MlKem768): 1088 bytes
/// Request (XWing): 1248 bytes
/// Response (XWing): 1120 bytes
use libcrux_kem::*;
use nym_crypto::hkdf::blake3::derive_key_blake3;
use nym_kkt_ciphersuite::{KEM, mceliece, ml_kem768, x25519, xwing};
use rand09::{CryptoRng, RngCore};
use std::fmt::{Debug, Formatter};
use zeroize::Zeroize;

use crate::error::KKTError;

/// Context string to be used with the Blake3 KDF.
const REKEY_CONTEXT: &str = "NYM_PQ_REKEY_v1";

pub struct RekeyInitiator {
    algorithm: Algorithm,
    decapsulation_key: PrivateKey,
    salt: [u8; 32],
}

impl Debug for RekeyInitiator {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let key_typ = match self.decapsulation_key {
            PrivateKey::X25519(_) => "x25519",
            PrivateKey::P256(_) => "p256",
            PrivateKey::MlKem512(_) => "ml512",
            PrivateKey::MlKem768(_) => "mlkem768",
            PrivateKey::X25519MlKem768Draft00(_) => "x25519-mlkem768",
            PrivateKey::XWingKemDraft06(_) => "xwing",
            PrivateKey::MlKem1024(_) => "ml1024",
        };

        f.debug_struct("RekeyInitiator")
            .field("algorithm", &self.algorithm)
            .field("decapsulation_key", &key_typ)
            .field("salt", &self.salt)
            .finish()
    }
}

impl RekeyInitiator {
    /// The Initiator generates an ephemeral KEM keypair and a 32-byte salt.
    /// The Initiator keeps the decapsulation key and generates a request message.
    /// The request message contains the salt and an encoding of the encapsulation key as follows
    ///      salt        encapsulation_key
    /// [0 ........ 32 | 32 .............. ]
    ///
    /// Inputs:
    /// rng: something that implements CryptoRng + RngCore
    /// kem: a KEM algorithm (we currently support MlKem768 and XWing)
    ///
    /// Outputs:
    /// RekeyInitiator: A struct which contains the decapsulation key, the salt and the kem algorithm in use.
    /// Vec<u8>: The request message as explained above. This is to be sent to the responder as-is.
    pub fn generate_request<R>(rng: &mut R, kem: KEM) -> Result<(RekeyInitiator, Vec<u8>), KKTError>
    where
        R: CryptoRng + RngCore,
    {
        let (algorithm, buffer_size) = match kem {
            // KEM::XWing => (Algorithm::XWingKemDraft06, 32 + xwing::PUBLIC_KEY_LENGTH),
            KEM::MlKem768 => (Algorithm::MlKem768, 32 + ml_kem768::PUBLIC_KEY_LENGTH),
            // We don't support McEliece because the keys are massive.
            // If this is a deal-breaker, users can start a new session with PSQ which can use McEliece.
            KEM::McEliece => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "McEliece is not supported for re-keying",
                });
            }
        };

        // Generate the Initiator's salt
        let mut salt = [0u8; 32];
        rng.fill_bytes(&mut salt);

        // Create the buffer for the request message and copy the salt into it.
        let mut request_buffer = Vec::with_capacity(buffer_size);
        request_buffer.extend_from_slice(&salt);

        // Generate the ephemeral KEM keypair based on the algorithm from the function's input.
        let (decapsulation_key, encapsulation_key) = key_gen(algorithm, rng)?;

        // Append the encoding of the KEM encapsulation key to the initiator's randomness.
        request_buffer.extend(encapsulation_key.encode());

        Ok((
            // The Initiator should store this until they use `RekeyInitiator::finalize`.
            RekeyInitiator {
                algorithm,
                decapsulation_key,
                salt,
            },
            // This is to be sent to the responder.
            request_buffer,
        ))
    }

    /// The Initiator will attempt to decapsulate the `pre_key` generated by the responder
    /// secret. This `pre_key` will be combined with the Initiator's previously generated salt
    /// as input to a Blake3 KDF call to generate the new shared secret.
    ///
    /// This function fails if the ciphertext cannot be decoded or decapsulated.
    ///
    /// Input:
    /// response_message: the responder's message which contains an encapsulation of `pre_key`.
    /// Output:
    /// [u8; 32]: the new shared secret.
    pub fn finalize(mut self, response_message: &[u8]) -> Result<[u8; 32], KKTError> {
        // Decode the responder's ciphertext.
        let ciphertext = Ct::decode(self.algorithm, response_message)?;
        // Decapsulate the `pre_key` using the Initiator's decapsulation key.
        let pre_key = ciphertext.decapsulate(&self.decapsulation_key)?;

        // Encode the `pre_key` into bytes
        let pre_key_bytes = pre_key.encode();

        let new_secret: [u8; 32] = derive_key_blake3(REKEY_CONTEXT, &pre_key_bytes, &self.salt);

        // Zeroize the Initiator's salt
        self.salt.zeroize();

        // TODO: zeroize the decapsulation key

        Ok(new_secret)
    }
}

/// The responder parses the request message.
/// The first 32 bytes are the Initiator's salt,
/// and the remainder is the encoding of the public key.
/// Given that XWing and MlKem768 have different key lengths,
/// we could deduce the algorithm from that.
///
/// If the message is badly formatted, or the encapsulation received is invalid,
/// this function will produce an error.
///
/// If everything is alright, the responder generates and encapsulates a key `pre_key` to send to the Initiator.
/// Then, the responder calls a Blake3 KDF over `pre_key` and the Initiator's salt to obtain
/// the new shared secret.
///
/// Inputs:
/// rng: something that implements CryptoRng + RngCore
/// request_message: the Initiator's request message (contains the salt and encapsulation key)
///
/// Outputs:
/// [u8; 32]: new shared secret
/// Vec<u8>: response which contains an encapsulation of a secret value generated by the responder.
/// This is to be sent back to the Initiator as-is.
pub fn responder_process<R>(
    rng: &mut R,
    mut request_message: Vec<u8>,
) -> Result<([u8; 32], Vec<u8>), KKTError>
where
    R: CryptoRng + RngCore,
{
    // Deduce the KEM algorithm from the message length
    let algorithm = match request_message.len().checked_sub(32) {
        //
        Some(num) => match num {
            // If message length is 1216 (32 + 1184) then the algorithm should be MlKem768
            ml_kem768::PUBLIC_KEY_LENGTH => Algorithm::MlKem768,
            // If message length is 1248 (32 + 1216) then the algorithm should be MlKem768
            xwing::PUBLIC_KEY_LENGTH => Algorithm::XWingKemDraft06,
            // We don't support McEliece because the keys are massive.
            // If this is a deal-breaker, users can start a new session with PSQ which can use McEliece.
            mceliece::PUBLIC_KEY_LENGTH => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "McEliece is not supported for re-keying",
                });
            }
            // We don't support X25519 because it's not post-quantum secure.
            x25519::PUBLIC_KEY_LENGTH => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "McEliece is not supported for re-keying",
                });
            }
            // Reject if the size does not match any of the above.
            _ => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "Unknown Algorithm",
                });
            }
        },
        // Reject if message length is less than 32.
        None => {
            return Err(KKTError::DecodingError {
                info: "Invalid rekey request: size is too small",
            });
        }
    };

    // Split the message to get the Initiator's salt (first 32 bytes)
    // and the encoding of the Initiator's public key.
    let (remote_salt, remote_encapsulation_key_bytes) = request_message.split_at_mut(32);

    // Attempt to decode the Initiator's encapsulation key.
    let remote_encapsulation_key = PublicKey::decode(algorithm, remote_encapsulation_key_bytes)?;

    // Encapsulate a fresh `pre_key` using the Initiator's encapsulation key into `ciphertext`.
    let (pre_key, ciphertext) = remote_encapsulation_key.encapsulate(rng)?;
    // Encode the ciphertext into bytes to send back to the initiator.
    let message = ciphertext.encode();

    // Encode the `pre_key` into bytes
    let pre_key_bytes = pre_key.encode();

    let new_secret: [u8; 32] = derive_key_blake3(REKEY_CONTEXT, &pre_key_bytes, remote_salt);

    // Zeroize the Initiator's salt
    remote_salt.zeroize();

    Ok((new_secret, message))
}

#[cfg(test)]
mod tests {
    use crate::error::KKTError;
    use crate::rekey::{RekeyInitiator, responder_process};
    use nym_kkt_ciphersuite::KEM;

    #[test]
    fn rekey_test() {
        let mut rng = rand09::rng();

        let (rekey_state, request_message) =
            RekeyInitiator::generate_request(&mut rng, KEM::MlKem768).unwrap();

        let (responder_secret, response_message) =
            responder_process(&mut rng, request_message).unwrap();

        let initiator_secret = rekey_state.finalize(&response_message).unwrap();

        assert_eq!(initiator_secret, responder_secret);

        // mceliece should fail
        let err = RekeyInitiator::generate_request(&mut rng, KEM::McEliece).unwrap_err();
        assert_eq!(
            err.to_string(),
            KKTError::UnsupportedAlgorithm {
                info: "McEliece is not supported for re-keying",
            }
            .to_string()
        )
    }
}
