use libcrux_kem::*;
use nym_kkt_ciphersuite::{KEM, mceliece, ml_kem768, x25519, xwing};
use rand::{CryptoRng, RngCore};
use zeroize::Zeroize;

use crate::error::KKTError;

/// This module implements a simple post-quantum re-keying protocol in one round-trip.
/// We currently support MlKem768 and Xwing.
///
/// This protocol is safe if it runs under a trusted secure channel.

const REKEY_CONTEXT: &str = "NYM_REKEY";

pub struct RekeyInitiator {
    algorithm: Algorithm,
    decapsulation_key: PrivateKey,
    randomness: [u8; 32],
}

impl RekeyInitiator {
    /// The initiator generates an ephemeral KEM keypair and 32 bytes of randomness.
    /// The initiator keeps the decapsulation key and generates a request message.
    /// The request message contains the random 32 bytes and an encoding of the encapsulation key as follows
    ///      rand        encapsulation_key
    /// [0 ........ 32 | 32 .............. ]
    ///
    /// Inputs:
    /// rng: something that implements CryptoRng + RngCore
    /// kem: a KEM algorithm (we currently support MlKem768 and XWing)
    ///
    /// Outputs:
    /// RekeyInitiator: A struct which contains the decapsulation key, the generated randomness and the kem algorithm in use.
    /// Vec<u8>: The request message as explained above. This is to be sent to the responder as-is.
    pub fn rekey_initiator<R>(rng: &mut R, kem: KEM) -> Result<(RekeyInitiator, Vec<u8>), KKTError>
    where
        R: CryptoRng + RngCore,
    {
        let mut randomness = [0u8; 32];
        rng.fill_bytes(&mut randomness);

        let mut output_vec: Vec<u8> = randomness.to_vec();

        let algorithm = match kem {
            KEM::XWing => Algorithm::XWingKemDraft06,
            KEM::MlKem768 => Algorithm::MlKem768,
            KEM::McEliece => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "McEliece is not supported for re-keying",
                });
            }
            KEM::X25519 => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "X25519 is not supported for re-keying",
                });
            }
        };

        let (decapsulation_key, encapsulation_key) = key_gen(algorithm, rng)?;

        output_vec.extend(encapsulation_key.encode());
        Ok((
            RekeyInitiator {
                algorithm,
                decapsulation_key,
                randomness,
            },
            output_vec,
        ))
    }

    /// The initiator will attempt to decapsulate the `pre_key` generated by the responder
    /// secret. This `pre_key` will be combined with the initiator's previously generated randomness
    /// as input to a Blake3 KDF call to generate the new shared secret.
    ///
    /// This function fails if the ciphertext cannot be decoded or decapsulated.
    ///
    /// Input:
    /// response_message: the responder's message which contains an encapsulation of `pre_key`.
    /// Output:
    /// [u8; 32]: the new shared secret.
    pub fn finalize(mut self, response_message: &[u8]) -> Result<[u8; 32], KKTError> {
        let ciphertext = Ct::decode(self.algorithm, response_message)?;
        let pre_key = ciphertext.decapsulate(&self.decapsulation_key)?;

        let mut to_hash = pre_key.encode();
        to_hash.extend_from_slice(&self.randomness);
        let new_secret: [u8; 32] = blake3::derive_key(REKEY_CONTEXT, &to_hash);

        self.randomness.zeroize();

        // todo zeroize

        Ok(new_secret)
    }
}

/// The responder parses the request message.
/// The first 32 bytes are the initiator's randomness,
/// and the remainder is the encoding of the public key.
/// Given that XWing and MlKem have different key lengths,
/// we could deduce the algorithm from that.
///
/// If the message is badly formatted, or the encapsulation received is invalid,
/// this function will produce an error.
///
/// If everything is alright, the responder generates and encapsulates a key `pre_key` to send to the initiator.
/// Then, the responder calls a Blake3 KDF over `pre_key` and the initiator's randomness to obtain
/// the new shared secret.
///
/// Inputs:
/// rng: something that implements CryptoRng + RngCore
/// request_message: the initiator's request message (contains randomness and an encapsulation key)
///
/// Outputs:
/// [u8; 32]: new shared secret
/// Vec<u8>: response which contains an encapsulation of a secret value generated by the responder.
/// This is to be sent back to the Initiator as-is.
pub fn rekey_responder<R>(
    rng: &mut R,
    mut request_message: Vec<u8>,
) -> Result<([u8; 32], Vec<u8>), KKTError>
where
    R: CryptoRng + RngCore,
{
    let algorithm = match request_message.len().checked_sub(32) {
        Some(num) => match num {
            ml_kem768::PUBLIC_KEY_LENGTH => Algorithm::MlKem768,
            xwing::PUBLIC_KEY_LENGTH => Algorithm::XWingKemDraft06,
            mceliece::PUBLIC_KEY_LENGTH => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "McEliece is not supported for re-keying",
                });
            }
            x25519::PUBLIC_KEY_LENGTH => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "McEliece is not supported for re-keying",
                });
            }
            _ => {
                return Err(KKTError::UnsupportedAlgorithm {
                    info: "Unknown Algorithm",
                });
            }
        },
        None => {
            return Err(KKTError::DecodingError {
                info: "Invalid rekey request: size is too small",
            });
        }
    };

    let (remote_randomness, remote_encapsulation_key_bytes) = request_message.split_at_mut(32);

    let remote_encapsulation_key = PublicKey::decode(algorithm, &remote_encapsulation_key_bytes)?;

    let (pre_key, ciphertext) = remote_encapsulation_key.encapsulate(rng).unwrap();
    let message = ciphertext.encode();

    let mut to_hash = pre_key.encode();
    to_hash.extend_from_slice(&remote_randomness);
    let new_secret: [u8; 32] = blake3::derive_key(REKEY_CONTEXT, &to_hash);

    remote_randomness.zeroize();

    Ok((new_secret, message))
}

#[cfg(test)]
mod tests {
    use nym_kkt_ciphersuite::KEM;

    use crate::rekey::{RekeyInitiator, rekey_responder};

    #[test]
    fn rekey_test() {
        let mut rng = rand::rng();

        for kem in [KEM::MlKem768, KEM::XWing] {
            let (rekey_state, request_message) =
                RekeyInitiator::rekey_initiator(&mut rng, kem).unwrap();

            let (responder_secret, response_message) =
                rekey_responder(&mut rng, request_message).unwrap();

            let initiator_secret = rekey_state.finalize(&response_message).unwrap();

            assert_eq!(initiator_secret, responder_secret);
        }
    }
}
