// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IHub is an autogenerated mock type for the IHub type
type IHub struct {
	mock.Mock
}

// Notify provides a mock function with given fields: msg
func (_m *IHub) Notify(msg []byte) {
	_m.Called(msg)
}
