// Copyright 2026 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: GPL-3.0-only

/// Environment variable names used as fallbacks for CLI arguments.
/// Each constant matches the `env = ...` attribute on the corresponding clap field.
pub mod vars {
    // common args
    pub const NYM_NETWORK_MONITOR_AGENT_SENDING_DURATION_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_SENDING_DURATION";
    pub const NYM_NETWORK_MONITOR_AGENT_WAITING_DURATION_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_WAITING_DURATION";
    pub const NYM_NETWORK_MONITOR_AGENT_TARGET_RATE_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_TARGET_RATE";
    pub const NYM_NETWORK_MONITOR_AGENT_REUSE_HEADER_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_REUSE_HEADER";
    pub const NYM_NETWORK_MONITOR_AGENT_NOISE_KEY_PATH_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NOISE_KEY_PATH";
    pub const NYM_NETWORK_MONITOR_AGENT_PACKET_DELAY_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_PACKET_DELAY";
    pub const NYM_NETWORK_MONITOR_AGENT_EGRESS_CONNECTION_TIMEOUT_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_EGRESS_CONNECTION_TIMEOUT";
    pub const NYM_NETWORK_MONITOR_AGENT_NOISE_HANDSHAKE_TIMEOUT_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NOISE_HANDSHAKE_TIMEOUT";
    pub const NYM_NETWORK_MONITOR_AGENT_SENDING_BATCH_SIZE_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_SENDING_BATCH_SIZE";

    // run agent args
    pub const NYM_NETWORK_MONITOR_AGENT_ORCHESTRATOR_ADDRESS_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_ORCHESTRATOR_ADDRESS";
    pub const NYM_NETWORK_MONITOR_AGENT_ORCHESTRATOR_TOKEN_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_ORCHESTRATOR_TOKEN";
    pub const NYM_NETWORK_MONITOR_AGENT_HOST_IP_ARG: &str = "NYM_NETWORK_MONITOR_AGENT_HOST_IP";

    // test node args
    pub const NYM_NETWORK_MONITOR_AGENT_MIXNET_ADDRESS_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_MIXNET_ADDRESS";
    pub const NYM_NETWORK_MONITOR_AGENT_NODE_ADDRESS_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NODE_ADDRESS";
    pub const NYM_NETWORK_MONITOR_AGENT_NODE_NOISE_KEY_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NODE_NOISE_KEY";
    pub const NYM_NETWORK_MONITOR_AGENT_NODE_SPHINX_KEY_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NODE_SPHINX_KEY";
    pub const NYM_NETWORK_MONITOR_AGENT_NODE_SPHINX_KEY_ROTATION_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NODE_SPHINX_KEY_ROTATION";
}
