// Copyright 2026 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: GPL-3.0-only

pub mod vars {
    // common args
    pub const NYM_NETWORK_MONITOR_AGENT_SENDING_DURATION_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_SENDING_DURATION";
    pub const NYM_NETWORK_MONITOR_AGENT_WAITING_DURATION_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_WAITING_DURATION";
    pub const NYM_NETWORK_MONITOR_AGENT_TARGET_RATE_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_TARGET_RATE";
    pub const NYM_NETWORK_MONITOR_AGENT_REUSE_HEADER_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_REUSE_HEADER";
    pub const NYM_NETWORK_MONITOR_AGENT_NOISE_KEY_PATH_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NOISE_KEY_PATH";
    pub const NYM_NETWORK_MONITOR_AGENT_PACKET_DELAY_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_PACKET_DELAY";

    // run agent args
    pub const NYM_NETWORK_MONITOR_AGENT_ORCHESTRATOR_ADDRESS_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_ORCHESTRATOR_ADDRESS";
    pub const NYM_NETWORK_MONITOR_AGENT_ORCHESTRATOR_TOKEN_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_ORCHESTRATOR_TOKEN";

    // test node args
    pub const NYM_NETWORK_MONITOR_AGENT_NODE_ADDRESS_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NODE_ADDRESS";
    pub const NYM_NETWORK_MONITOR_AGENT_NODE_NOISE_KEY_ARG: &str =
        "NYM_NETWORK_MONITOR_AGENT_NODE_NOISE_KEY";
}
