// Copyright 2024 - Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: GPL-3.0-only

pub mod vars {
    pub const NYMNODE_ID_ARG: &str = "NYMNODE_ID";
    pub const NYMNODE_CONFIG_PATH_ARG: &str = "NYMNODE_CONFIG";

    pub const NYMNODE_DENY_INIT_ARG: &str = "NYMNODE_DENY_INIT";

    pub const NYMNODE_INIT_ONLY_ARG: &str = "NYMNODE_INIT_ONLY";

    pub const NYMNODE_MODE_ARG: &str = "NYMNODE_MODE";

    // host:
    pub const NYMNODE_PUBLIC_IPS_ARG: &str = "NYMNODE_PUBLIC_IPS";
    pub const NYMNODE_HOSTNAME_ARG: &str = "NYMNODE_HOSTNAME";
    pub const NYMNODE_HTTP_ACCESS_TOKEN_ARG: &str = "NYMNODE_HTTP_ACCESS_TOKEN";

    // http:
    pub const NYMNODE_HTTP_BIND_ADDRESS_ARG: &str = "NYMNODE_HTTP_BIND_ADDRESS";
    pub const NYMNODE_HTTP_LANDING_ASSETS_ARG: &str = "NYMNODE_HTTP_LANDING_ASSETS";

    // mixnet:
    pub const NYMNODE_MIXNET_BIND_ADDRESS_ARG: &str = "NYMNODE_MIXNET_BIND_ADDRESS";
    pub const NYMNODE_NYM_APIS_ARG: &str = "NYMNODE_NYM_APIS";

    // wireguard:
    pub const NYMNODE_WG_ENABLED_ARG: &str = "NYMNODE_WG_ENABLED";
    pub const NYMNODE_WG_BIND_ADDRESS_ARG: &str = "NYMNODE_WG_BIND_ADDRESS";
    pub const NYMNODE_WG_ANNOUNCED_PORT_ARG: &str = "NYMNODE_WG_ANNOUNCED_PORT";
    pub const NYMNODE_WG_PRIVATE_NETWORK_PREFIX_ARG: &str = "NYMNODE_WG_PRIVATE_NETWORK_PREFIX";

    // mixnode:
    pub const NYMNODE_VERLOC_BIND_ADDRESS_ARG: &str = "NYMNODE_VERLOC_BIND_ADDRESS";

    // entry gateway:
    pub const NYMNODE_ENTRY_BIND_ADDRESS_ARG: &str = "NYMNODE_ENTRY_BIND_ADDRESS";
    pub const NYMNODE_ENTRY_ANNOUNCE_WS_PORT_ARG: &str = "NYMNODE_ENTRY_ANNOUNCE_WS_PORT";
    pub const NYMNODE_ENTRY_ANNOUNCE_WSS_PORT_ARG: &str = "NYMNODE_ENTRY_ANNOUNCE_WSS_PORT";
    pub const NYMNODE_ENFORCE_ZK_NYMS_ARG: &str = "NYMNODE_ENFORCE_ZK_NYMS";
    pub const NYMNODE_MNEMONIC_ARG: &str = "NYMNODE_MNEMONIC";

    // exit gateway:

    pub const NYMMONDE_WRITE_CONFIG_CHANGES_ARG: &str = "NYMNODE_WRITE_CONFIG_CHANGES";

    // pub const MIXNODE_ID_ARG: &str = "NYM_MIXNODE_ID";
    // pub const MIXNODE_LISTENING_ADDRESS_ARG: &str = "NYM_MIXNODE_LISTENING_ADDRESS";
    // pub const MIXNODE_MIX_PORT_ARG: &str = "NYM_MIXNODE_MIX_PORT";
    // pub const MIXNODE_VERLOC_PORT_ARG: &str = "NYM_MIXNODE_VERLOC_PORT";
    // pub const MIXNODE_HTTP_API_PORT_ARG: &str = "NYM_MIXNODE_HTTP_API_PORT";
    // pub const MIXNODE_NYM_APIS_ARG: &str = "NYM_MIXNODE_NYM_APIS";
    // pub const MIXNODE_OUTPUT_ARG: &str = "NYM_MIXNODE_OUTPUT";
}
