// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppVersion {
  current_version: string;
  latest_version: string;
  is_update_available: boolean;
}
