name: nightly-security-audit

on:
  schedule:
    - cron: '5 9 * * *'
jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ vars.REQUIRED_RUSTC_VERSION }}
      - name: Install cargo deny
        run: cargo install --locked cargo-deny
      - name: Run cargo deny
        run: |
          find . -name Cargo.toml -exec cargo deny --manifest-path {} check \
            advisories -A advisory-not-detected  --hide-inclusion-graph \; &> \
            >(uniq  &> .github/workflows/support-files/notifications/deny.message )
      - uses: actions/upload-artifact@v7
        with:
          name: report
          path: .github/workflows/support-files/notifications/deny.message
