#ifndef CONSTS_NAMESPACE_H
#define CONSTS_NAMESPACE_H

#define hh1_p1 CRYPTO_SHARED_NAMESPACE(hh1_p1)
#define hh1_p2 CRYPTO_SHARED_NAMESPACE(hh1_p2)
#define h2h_p1 CRYPTO_SHARED_NAMESPACE(h2h_p1)
#define h2h_p2 CRYPTO_SHARED_NAMESPACE(h2h_p2)
#define hh1_xor CRYPTO_SHARED_NAMESPACE(hh1_xor)
#define h2h_xor CRYPTO_SHARED_NAMESPACE(h2h_xor)
#define swap_c CRYPTO_SHARED_NAMESPACE(swap_c)
#define swap_mask CRYPTO_SHARED_NAMESPACE(swap_mask)
#define h2h_mask CRYPTO_SHARED_NAMESPACE(h2h_mask)
#define vec19 CRYPTO_SHARED_NAMESPACE(vec19)
#define vec38 CRYPTO_SHARED_NAMESPACE(vec38)
#define vecmask25 CRYPTO_SHARED_NAMESPACE(vecmask25)
#define vecmask26 CRYPTO_SHARED_NAMESPACE(vecmask26)
#define vecmask32 CRYPTO_SHARED_NAMESPACE(vecmask32)
#define a24 CRYPTO_SHARED_NAMESPACE(a24)
#define mask63 CRYPTO_SHARED_NAMESPACE(mask63)

#endif //ifndef CONSTS_NAMESPACE_H

